companyfinder/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from main.views import IndexPageView,comp,uploadimg,CompanyDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("uploadimage/",uploadimg),
    path('getcompanydetails/<int:pk>', login_required(CompanyDetailView.as_view(),login_url='/login/')),
    path('', IndexPageView.as_view(), name='index'),
    path('profile/', login_required(comp.as_view(),login_url='/login/'), name='profile'),
    path('accounts/', include('main.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import (
     LoginView,SignUpView,CreateProfileView,LogOutView,CreateCompanyView)

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='log_in'),
    path('createprofile/',CreateProfileView.as_view(),name="create_profile"),
    path('createcompany/',CreateCompanyView.as_view(),name="create_company"),
    path('logout/', LogOutView.as_view(), name='log_out'),
    path('signup/', SignUpView.as_view(), name='sign_up'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Company(models.Model):
	name=models.CharField(max_length=100)
	logo=models.ImageField(default='/company.jpg')
	address=models.CharField(max_length=200)

	def __str__(self):
		return self.name

class UserProfile(models.Model):
    user   = models.OneToOneField(User,on_delete=models.CASCADE)
    avatar = models.ImageField(default='/happyprofile.jpg')
    job=models.CharField(max_length=100)
    company=models.ForeignKey(Company,on_delete=models.SET_NULL,null=True)

    def __str__(self):
    	return self.user.username

main/forms.py
from django import forms
from .models import *

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['job','company']

    def __init__(self, *args, **kwargs):
    	self.request = kwargs.pop('request')
    	super(ProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.user = self.request.user
        return super().save(commit=commit)
        
class Companyform(forms.ModelForm):
	class Meta:
		model=Company
		exclude=('logo',)

main/views.py
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)

from django.views.generic import View, FormView
from django.conf import settings

from django.shortcuts import render, redirect,HttpResponse

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.views.generic import *
from hitcount.views import HitCountDetailView
from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
from django.contrib.auth.models import User
from .models import *
from .forms import *


class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    success_url = '/profile/'
    template_name='login.html'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.POST.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to



class CompanyDetailView(HitCountDetailView):
    model=Company
    slug_field = 'pk'
    slug_url_kwarg = 'pk'
    queryset = Company.objects.filter()
    context_object_name = 'company'
    count_hit = True
    template_name="company_detail.html"






class SignUpView(FormView):
    form_class = UserCreationForm
    template_name = 'signup.html'

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return redirect('/accounts/createprofile/')

class CreateProfileView(FormView):
    form_class = ProfileForm
    template_name = 'CreateProfile.html'

    def get_form_kwargs(self):
        kwargs = super(CreateProfileView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        print(form.cleaned_data.get('avatar'))
        form.save()
        return redirect('/profile/')

class CreateCompanyView(FormView):
    form_class = Companyform
    template_name = 'Createcompany.html'
    success_url="/"

    def form_valid(self, form):
        form.save()
        return HttpResponse('<script type="text/javascript">window.close()</script>')



from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def uploadimg(request):
    print(request.POST)
    return HttpResponse("aj")


class LogOutView(LoginRequiredMixin, BaseLogoutView):
    template_name = 'logout.html'




class comp(TemplateView):
    template_name = 'main/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        par_obj=UserProfile.objects.get(user=self.request.user)
        print(par_obj)
        # par2_obj=Participants.objects.all()

        context['users'] = par_obj
        context['show']=True


        return context

class IndexPageView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        par_obj=UserProfile.objects.all()
        print(par_obj)
        # par2_obj=Participants.objects.all()

        if par_obj.count()!=0:
        	context['users'] = par_obj
        	context['show']=True
        else:
        	context['data'] = "No users registered"
        	context['show']=False


        return context

content/templates/layouts/default/page.html
{% load staticfiles %}
{% load bootstrap4 %}
{% load i18n %}



<!DOCTYPE html>
<html lang="eng">
<head>



    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">




    <style type="text/css">
        body {
            width: 100wh;
            height: 90vh;
            background: linear-gradient(-45deg, #EE7752, #E73C7E, #23A6D5, #23D5AB);
            background-size: 400% 400%;
            -webkit-animation: Gradient 15s ease infinite;
            -moz-animation: Gradient 15s ease infinite;
            animation: Gradient 15s ease infinite;
          }

          @-webkit-keyframes Gradient {
            0% {
              background-position: 0% 50%
            }
            50% {
              background-position: 100% 50%
            }
            100% {
              background-position: 0% 50%
            }
          }

          @-moz-keyframes Gradient {
            0% {
              background-position: 0% 50%
            }
            50% {
              background-position: 100% 50%
            }
            100% {
              background-position: 0% 50%
            }
          }

          @keyframes Gradient {
            0% {
              background-position: 0% 50%
            }
            50% {
              background-position: 100% 50%
            }
            100% {
              background-position: 0% 50%
            }
          }

          h1,
          h6 {
            font-family: 'Open Sans';
            font-weight: 300;
            text-align: center;
            position: absolute;
            top: 45%;
            right: 0;
            left: 0;
          }
        .login {
          overflow: hidden;
          background-color: white;
          padding: 40px 30px 30px 30px;
          border-radius: 10px;
          width: 400px;
          -webkit-transform: translate(-50%, -50%);
          -moz-transform: translate(-50%, -50%);
          -ms-transform: translate(-50%, -50%);
          -o-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
          -webkit-transition: -webkit-transform 300ms, box-shadow 300ms;
          -moz-transition: -moz-transform 300ms, box-shadow 300ms;
          transition: transform 300ms, box-shadow 300ms;
          box-shadow: 5px 10px 10px rgba(2, 128, 144, 0.2);
        }
        .login::before, .login::after {
          content: '';
          position: absolute;
          width: 600px;
          height: 600px;
          border-top-left-radius: 40%;
          border-top-right-radius: 45%;
          border-bottom-left-radius: 35%;
          border-bottom-right-radius: 40%;
          z-index: -1;
        }
        .login::before {
          left: 40%;
          bottom: -130%;
          background-color: rgba(69, 105, 144, 0.15);
          -webkit-animation: wawes 6s infinite linear;
          -moz-animation: wawes 6s infinite linear;
          animation: wawes 6s infinite linear;
        }
        .login::after {
          left: 35%;
          bottom: -125%;
          background-color: rgba(2, 128, 144, 0.2);
          -webkit-animation: wawes 7s infinite;
          -moz-animation: wawes 7s infinite;
          animation: wawes 7s infinite;
        }
        .login > input {
          font-family: "Asap", sans-serif;
          display: block;
          border-radius: 5px;
          font-size: 16px;
          background: white;
          width: 100%;
          border: 0;
          padding: 10px 10px;
          margin: 15px -10px;
        }
        .login > button {
          font-family: "Asap", sans-serif;
          cursor: pointer;
          color: #fff;
          font-size: 16px;
          text-transform: uppercase;
          width: 80px;
          border: 0;
          padding: 10px 0;
          margin-top: 10px;
          margin-left: -5px;
          border-radius: 5px;
          background-color: #f45b69;
          -webkit-transition: background-color 300ms;
          -moz-transition: background-color 300ms;
          transition: background-color 300ms;
        }
        .login > button:hover {
          background-color: #f24353;
        }

        @-webkit-keyframes wawes {
          from {
            -webkit-transform: rotate(0);
          }
          to {
            -webkit-transform: rotate(360deg);
          }
        }
        @-moz-keyframes wawes {
          from {
            -moz-transform: rotate(0);
          }
          to {
            -moz-transform: rotate(360deg);
          }
        }
        @keyframes wawes {
          from {
            -webkit-transform: rotate(0);
            -moz-transform: rotate(0);
            -ms-transform: rotate(0);
            -o-transform: rotate(0);
            transform: rotate(0);
          }
          to {
            -webkit-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -ms-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
          }
        }

    </style>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/"><strong>{% trans 'Company Finder' %}</strong></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Login' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li>
            {% endif %}
        </ul>

    </div>

</nav>

<div class="container-fluid mt-3" style="padding:25px;">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>

<script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

content/templates/main/hunt.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
<style type="text/css">
	.g{
  color:#4285F4;
}
.o{
  color:#EA4335;
}
.o1{
  color:#FBBC05;
}
.l{
  color:#34A853;
}
.e{
  color:#EA4335;
}
body{
   margin: 5px 5px 5px 5px;
}

.card-1 {
  padding: 10px 10px 10px 10px;
  box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
}

hr {
     color: #f00;
     background: #e0e0e0; 
     width: 100%; 
     height: 10%;
     box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
}
.bold{
    font-family: Helvetica;
    font-weight: bold;
}
.table-responsive>.table>tbody>tr>td{
    horizontal-align: middle;
}
.card {
  margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
}
</style>

    
		
<script>
  $(document).ready(function(){
    $("#card1").css("center-block")   
});
</script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container-fluid">
  <h1 class="text-md-center">{{user.first_name}} {{user.last_name}}</h1>
  <div class="container">
    <div class="row">
      <div class="container-fluid">
<image src="/media/happyprofile.jpg" width="350px">
  <div class="caption text-md-center"><em>Chief Executive Officer of Alphabet Inc.</em></div>
  </div>
     <hr>
 <!--CARDS start here-->
        <div class="card card-1 col-md-6 text-md-center" id="card1">
        <table class="table table-hover">
  <tbody>
    <tr>
      <td><span class="bold">Title</span></td>
      <td colspan="2">CEO of Alphabet Inc</td>
    </tr>

  </tbody>
</table>
        </div>       

  </div>
         <hr>
</div>	    

{% endblock %}

content/templates/main/index.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
<style type="text/css">
	/* Style the tab */
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
  font-size: 17px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
  background-color: lightyellow;
}

</style>
	<div class="tab">
	  <button class="tablinks active">Registered Users</button>
	</div>

	<div class="tabcontent" style="display: block;">
		
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Username</th>
		      <th scope="col">company</th>
		    </tr>
		  </thead>
		  <tbody>
		  {% for user in users %}
			<tr>
		      <th scope="row">{{ forloop.counter }}</th>
		      <td>{{ user.user.username }}</td>
		      <td>{{ user.company }}</td>
		    </tr>
		   {% endfor %}
		
		  </tbody>
		</table>
	</div>	

{% endblock %}

content/templates/main/profile.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
<style type="text/css">
	.g{
  color:#4285F4;
}
.o{
  color:#EA4335;
}
.o1{
  color:#FBBC05;
}
.l{
  color:#34A853;
}
.e{
  color:#EA4335;
}
body{
   margin: 5px 5px 5px 5px;
}

.card-1 {
  padding: 10px 10px 10px 10px;
  box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
}

hr {
     color: #f00;
     background: #e0e0e0; 
     width: 100%; 
     height: 10%;
     box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
}
.bold{
    font-family: Helvetica;
    font-weight: bold;
}
.table-responsive>.table>tbody>tr>td{
    horizontal-align: middle;
}
.card {
  margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
}
</style>

    
		
<script>
  $(document).ready(function(){
    $("#card1").css("center-block")   
});
</script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container-fluid">
  <h1 class="text-md-center">{{user}} {{user.last_name}}</h1>
  <div class="container">
    <div class="row">
      <div class="container-fluid">


<image src="/media/{{users.avatar}}" width="350px">
  <div class="caption text-md-center"><em>{{users.job}}</em></div>
  </div>
     <hr>

        <div class="card card-1 col-md-6 text-md-center" id="card1">
        <table class="table table-hover">
  <tbody>
     <tr>
      <td><span class="bold">Name</span></td>
      <td colspan="2">{{users}}</td>
    </tr>
    <tr>
      <td><span class="bold">Job</span></td>
      <td colspan="2">{{users.job}}</td>
    </tr>
        <tr>
      <td><span class="bold">Comapany</span></td>
      <td colspan="2"><a href="/getcompanydetails/{{users.company.pk}}">{{users.company}}</a></td> 
    </tr>

  </tbody>
</table>
        </div>       

  </div>

         <hr>
</div>	    
{% endblock %}

main/templates/CreateProfile.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Add Details' %}</h4>
	<div class="container" style="
    border-style: solid;
    border-radius: 10px;
    padding: 25px;
    box-shadow: beige;
    box-shadow: 10px 10px lightgray;
    background: whitesmoke;
">
	    <form method="post">

	        {% csrf_token %}
	        {% bootstrap_form form %}
	        <a href="/accounts/createcompany" id="add_author" onclick="return showAddPopup(this);"><img src = "media/images/icon-addlink.svg">Company Not listed Here!</a>


	        <button class="btn btn-success">{% trans 'Create' %}</button>

	    </form>
	</div>
	<script type="text/javascript">
function showEditPopup(url) {
    var win = window.open(url, "Edit", 
        'height=500,width=800,resizable=yes,scrollbars=yes');
    return false;
}
function showAddPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    href = triggeringLink.href;
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;


    

}
function closePopup(win, newID, newRepr, id) {
    $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
    win.close();
    window.location.reload();

}

</script>
{% endblock %}

main/templates/Createcompany.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}
    <div class="container">
    <h4>{% trans 'Add Company' %}</h4>
        <form method="post" class="login" style="margin-top: 150px;position: relative;left: 50%;">

            {% csrf_token %}
            {% bootstrap_form form %}

            <button class="btn btn-primary">{% trans 'Add' %}</button>
        </form>
    
    <hr>
    </div>
{% endblock %}

main/templates/company_detail.html
{% extends 'layouts/default/page.html' %}
{% load hitcount_tags %}

{% load i18n %}

{% block content %}
<style type="text/css">
	.card-horizontal {
    display: flex;
    flex: 1 1 auto;
}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="card">
                <div class="card-horizontal">
                    <div class="img-square-wrapper">
                        <img class="" src="/media/{{company.logo}}" alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{company.name}}</h4>
                        <p class="card-text">{{company.address}}</p>
                    </div>
                </div>
                <div class="card-footer">
                    <small class="text-muted"></small>
                </div>
            </div>
        </div>
    </div>
            <div class="card card-1 col-md-6 text-md-center" id="card1">
        <table class="table table-hover">
  <tbody>
    <tr>
      <td><span class="bold">Address</span></td>
      <td colspan="2">{{company.address}}</td>
    </tr>
        <tr>
      <td><span class="bold">Hit counts</span></td>
      <td colspan="2">{{ hitcount.total_hits }}</td> 
    </tr>
     <tr>
      <td><span class="bold">Numbers of Users Online</span></td>
      <td colspan="2">{{ request.online_now.count }}</td> 
    </tr>





  </tbody>
</table>
        </div>
</div>


{% endblock %}

main/templates/login.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}
    <div class="container">
    <h4>{% trans 'Log in' %}</h4>
        <form method="post" class="login" style="margin-top: 150px;position: relative;left: 50%;">

            {% csrf_token %}
            {% bootstrap_form form %}

            <button class="btn btn-primary">{% trans 'Log in' %}</button>
        </form>
    
    <hr>
    </div>
{% endblock %}

main/templates/logout.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

main/templates/main/index.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}
sjdhfnskqlwksdjfbn

    {% if request.user.is_authenticated %}

        {% trans 'Your username is' %} <b>{{ request.user.username }}</b>.
		<div class="card-deck">
		  <div class="card">
		    <img class="card-img-top" src="..." alt="Card image cap">
		    <div class="card-body">
		      <h5 class="card-title">Card title</h5>
		      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
		    </div>
		    <div class="card-footer">
		      <small class="text-muted">Last updated 3 mins ago</small>
		    </div>
		  </div>
		  <div class="card">
		    <img class="card-img-top" src="..." alt="Card image cap">
		    <div class="card-body">
		      <h5 class="card-title">Card title</h5>
		      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
		    </div>
		    <div class="card-footer">
		      <small class="text-muted">Last updated 3 mins ago</small>
		    </div>
		  </div>
		  <div class="card">
		    <img class="card-img-top" src="..." alt="Card image cap">
		    <div class="card-body">
		      <h5 class="card-title">Card title</h5>
		      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
		    </div>
		    <div class="card-footer">
		      <small class="text-muted">Last updated 3 mins ago</small>
		    </div>
		  </div>
		</div>
	
    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

{% endblock %}

main/templates/signup.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Create an account' %}</h4>
	<div class="container" style="
    border-style: solid;
    border-radius: 10px;
    padding: 25px;
    box-shadow: beige;
    box-shadow: 10px 10px lightgray;
    background: whitesmoke;
">
	    <form method="post">

	        {% csrf_token %}
	        {% bootstrap_form form %}

	        <button class="btn btn-success">{% trans 'Create' %}</button>

	    </form>
	</div>
{% endblock %}